apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: covid-19-folding
spec:
  environments:
    - name: dev
      build:
        from: master

  components:
    - name: node1
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "30000m"
          replicas: 1
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'FULL'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY
        
    - name: node2
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "8000m"
          replicas: 1
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'FULL'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY
            
     
    - name: node3
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "8000m"
          replicas: 1
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'FULL'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY

    - name: node4
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "8000m"
          replicas: 1
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'FULL'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY
        
    - name: node5
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "8000m"
          replicas: 1
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'FULL'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY
