apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: covid-19-folding
spec:
  environments:
    - name: dev
      build:
        from: master

  components:
    - name: folding
      src: foldingathome
      ports:
        - name: http
          port: 7396
      publicPort: http
      environmentConfig:
        - environment: dev
          replicas: 2
          variables:
            USER: 'Kristian_Reed'
            TEAM: '254927'
            POWER: 'medium'
            CAUSE: 'COVID_19'
      secrets:
        - PASSWORD
        - PASSKEY
